import type { components, paths } from './schema';

export type Schemas = components['schemas'];
export type Paths = paths;

export type MeOut = Schemas['MeOut'];
export type DashboardSalesOut = Schemas['DashboardSalesOut'];
export type SalesOrderListItem = Schemas['SalesOrderListItemOut'];
export type TokenPair = Schemas['TokenPair'];
export type SalesOrderDetail = Schemas['SalesOrderDetailOut'];
export type SalesOrderIn = Schemas['SalesOrderIn'];
export type SalesOrderPatch = Schemas['SalesOrderPatch'];
export type SalesOrderCancelIn = Schemas['SalesOrderCancelIn'];
export type TimelineOut = Schemas['TimelineOut'];
export type TimelineItem = Schemas['TimelineItemOut'];
export type CustomerOut = Schemas['CustomerOut'];
export type CustomerDetailOut = Schemas['CustomerDetailOut'];
export type CustomerIn = Schemas['CustomerIn'];
export type CustomerFinancialSummary = Schemas['CustomerFinancialSummaryOut'];
export type ContactOut = Schemas['ContactOut'];
export type CustomerTypeOut = Schemas['CustomerTypeOut'];
export type PaymentTermOut = Schemas['PaymentTermOut'];
export type CategoryOut = Schemas['CategoryOut'];
export type DuplicateCheckIn = Schemas['DuplicateCheckIn'];
export type DuplicateCheckOut = Schemas['DuplicateCheckOut'];
export type DuplicateMatch = Schemas['DuplicateMatchOut'];
export type SalesOrderLine = Schemas['SalesOrderLineOut'];
export type SalesOrderSummary = Schemas['SalesOrderSummaryOut'];
export type SalesOrderWarning = Schemas['SalesOrderWarningOut'];
export type DeliveryNoteSummary = Schemas['DeliveryNoteSummaryOut'];
export type InvoiceSummary = Schemas['InvoiceSummaryOut'];
export type OrderPaymentSummary = Schemas['OrderPaymentSummaryOut'];
export type Shortage = Schemas['ShortageOut'];
export type DeliveryNoteDetail = Schemas['DeliveryNoteDetailOut'];
export type InvoiceDetail = Schemas['InvoiceDetailOut'];
export type PaymentDetail = Schemas['PaymentDetailOut'];
