export const keys = {
  me: ['me'] as const,
  version: ['app-version'] as const,
  dashboard: (salesUserId?: string | null) => ['dashboard', salesUserId ?? null] as const,
  orders: (params: Record<string, unknown>) => ['orders', params] as const,
  order: (id: string) => ['order', id] as const,
  orderTimeline: (id: string) => ['order', id, 'timeline'] as const,
  customers: (params: Record<string, unknown>) => ['customers', params] as const,
  customer: (id: string) => ['customer', id] as const,
  customerFinancialSummary: (id: string) => ['customer', id, 'financial-summary'] as const,
  products: (params: Record<string, unknown>) => ['products', params] as const,
  product: (id: string) => ['product', id] as const,
  variants: (q: string) => ['variants', q] as const,
  deliveryNote: (id: string) => ['delivery-note', id] as const,
  invoice: (id: string) => ['invoice', id] as const,
  masters: (name: string) => ['masters', name] as const,
};
